// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcg3U4r1YJKfK4g0z_tOHcFyfAu8etZLY',
    appId: '1:280879038347:web:0ac3644f251173b190f98e',
    messagingSenderId: '280879038347',
    projectId: 'resalate-a3ad0',
    authDomain: 'resalate-a3ad0.firebaseapp.com',
    storageBucket: 'resalate-a3ad0.firebasestorage.app',
    measurementId: 'G-Z7M3PL4MH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi9he1qhMHxJB1oY0UkuM0WtKEPe6OVAw',
    appId: '1:280879038347:android:23cb334a7b89242790f98e',
    messagingSenderId: '280879038347',
    projectId: 'resalate-a3ad0',
    storageBucket: 'resalate-a3ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbg4FU-u0NS3nDxR2uTdTmx79if40ZABc',
    appId: '1:280879038347:ios:02a6ced19803d55390f98e',
    messagingSenderId: '280879038347',
    projectId: 'resalate-a3ad0',
    storageBucket: 'resalate-a3ad0.firebasestorage.app',
    iosBundleId: 'com.resalate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbg4FU-u0NS3nDxR2uTdTmx79if40ZABc',
    appId: '1:280879038347:ios:02a6ced19803d55390f98e',
    messagingSenderId: '280879038347',
    projectId: 'resalate-a3ad0',
    storageBucket: 'resalate-a3ad0.firebasestorage.app',
    iosBundleId: 'com.resalate.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcg3U4r1YJKfK4g0z_tOHcFyfAu8etZLY',
    appId: '1:280879038347:web:aa0adbe2a471f96f90f98e',
    messagingSenderId: '280879038347',
    projectId: 'resalate-a3ad0',
    authDomain: 'resalate-a3ad0.firebaseapp.com',
    storageBucket: 'resalate-a3ad0.firebasestorage.app',
    measurementId: 'G-ZHHWN20GD5',
  );
}
